"""渲染器协议 —— 对应 ``com.paicli.render.Renderer`` 接口。"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, runtime_checkable

if TYPE_CHECKING:
    from suncli_py.hitl.approval_request import ApprovalRequest
    from suncli_py.hitl.approval_result import ApprovalResult
    from suncli_py.llm.models import ToolCall


@runtime_checkable
class Renderer(Protocol):
    """终端输出渲染器协议（extends AutoCloseable in Java）。"""

    def start(self) -> None: ...
    def close(self) -> None: ...
    def begin_turn(self) -> None: ...
    def finish_turn(self, final_answer: str) -> None: ...
    def stream(self) -> Any: ...  # Returns PrintStream-equivalent
    def begin_thinking(self, label: str) -> None: ...
    def append_thinking(self, delta: str) -> None: ...
    def end_thinking(self) -> None: ...
    def append_assistant_content_delta(self, delta: str) -> None: ...
    def finish_assistant_content(self) -> None: ...
    def append_tool_calls(self, tool_calls: list[ToolCall]) -> None: ...
    def append_diff(self, file_path: str, before: str, after: str) -> None: ...
    def update_status(self, status: Any) -> None: ...
    def prompt_approval(self, request: ApprovalRequest) -> ApprovalResult: ...
    def open_palette(self, title: str, items: list[str]) -> int: ...  # Returns selected index
    def before_input(self) -> None: ...
    def after_input(self) -> None: ...
    def begin_activity(self, label: str, detail: str = "") -> None: ...
    def end_activity(self) -> None: ...
    def input_prompt(self) -> str: ...
    def input_right_prompt(self) -> str: ...
    def terminal_columns(self) -> int: ...

    @property
    def supports_thinking_panel(self) -> bool:
        return False

    @property
    def supports_activity_panel(self) -> bool:
        return self.supports_thinking_panel

    def renders_reasoning(self) -> bool:
        return True
